common:
  CONFIGURATION_FILES:
    TESTING: '%%CONF_PATH%%testing.yml'
  MAIN_PATH: '%%BASE_PATH%%src/main/'
  RESOURCES_PATH: '%%MAIN_PATH%%resources/'
  CONF_PATH: '%%RESOURCES_PATH%%config/'
  TEST_PATH: '%%BASE_PATH%%src/test/'
  VENDOR_PATH: '%%BASE_PATH%%vendor/'
  DEFAULT:
    TEMPLATE:
      FILE: 'index'
      FILE_FORMAT: 'html'

